# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f3ce7599f1e2b70465cfd0ae58b6332fb4cffec0f1aadd43901fed54f6341657a815c4a0d5ad06173052e8241d04eaec25e8473184d19a192d4af02f96d5a30

test:
  secret_key_base: 5b53c3b1b9ae9f51c9890d4253c01a13f927fb36700e6e66f67174b046c7cd1605977a40d7f1b2c7b039939326e5c53ad6234de24b9fd225113e45ee0d2081b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
